### ISSUE TITLE
Change Rewards and Perks Section Image

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#290]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196420467-d5e8c04a-a4dd-4917-89b2-ef51cda3790f.png)

**Comment by durgeshm01722** [comment]
@Debajyoti14 Can you assign this to me?

**Comment by durgeshm01722** [comment]
Fixed this issue in PR no - #288 

![Screenshot 2022-10-18 182635](https://user-images.githubusercontent.com/85431456/196436713-767a2d2b-94b4-4aa2-9492-673b0aa614fc.png)

**Comment by Debajyoti14** [comment]
@durgeshm01722 The alignment looks weird.
As the image is too big, the right side content should be vertically centered.

**Comment by durgeshm01722** [comment]
Done 👍

Centering it completely in the vertical direction will make it look somewhat weird because there will be a lot of white space between the heading and the content. That's why centered it in this way. Is it fine?

![Screenshot 2022-10-18 203704](https://user-images.githubusercontent.com/85431456/196470408-279b58ed-3d37-446a-b191-fe3c5e694e00.png)
